In [1]:
import pandas as pd
import numpy as np
 
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
X = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
y = raw_df.values[1::2,2]

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
C:\Users\hp\AppData\Local\Temp\ipykernel_6276\2477648824.py:5: SyntaxWarning: invalid escape sequence '\s'
  raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)


In [3]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [5]:
X[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [7]:
X[3]

array([3.2370e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
       6.9980e+00, 4.5800e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
       1.8700e+01, 3.9463e+02, 2.9400e+00])

In [45]:
raw_df[random.sample(list(raw_df.columns),3)]

2      4      5
0      2.31  0.538  6.575
2      7.07  0.469  6.421
4      7.07  0.469  7.185
6      2.18  0.458  6.998
8      2.18  0.458  7.147
...     ...    ...    ...
1002  11.93  0.573  6.593
1004  11.93  0.573  6.120
1006  11.93  0.573  6.976
1008  11.93  0.573  6.794
1010  11.93  0.573  6.030

[506 rows x 3 columns]

In [143]:
np.array(raw_df[random.sample(list(raw_df.columns),3)])

array([[6.5750e+00, 6.3200e-03, 6.5200e+01],
       [6.4210e+00, 2.7310e-02, 7.8900e+01],
       [7.1850e+00, 2.7290e-02, 6.1100e+01],
       ...,
       [6.9760e+00, 6.0760e-02, 9.1000e+01],
       [6.7940e+00, 1.0959e-01, 8.9300e+01],
       [6.0300e+00, 4.7410e-02, 8.0800e+01]])

In [49]:
raw_df[random.sample(list(raw_df.columns),3)]

2     10    6 
0      2.31  15.3  65.2
2      7.07  17.8  78.9
4      7.07  17.8  61.1
6      2.18  18.7  45.8
8      2.18  18.7  54.2
...     ...   ...   ...
1002  11.93  21.0  69.1
1004  11.93  21.0  76.7
1006  11.93  21.0  91.0
1008  11.93  21.0  89.3
1010  11.93  21.0  80.8

[506 rows x 3 columns]

In [55]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [115]:
def multiple_linear_regression(X,y):
    ml_model=LinearRegression()
    X_train,X_test,y_train,y_test=train_test_split(X,y)
    ml_model.fit(X_train,y_train)
    y_pred=ml_model.predict(X_test)
    score=r2_score(y_test,y_pred)*100
    mse=mean_squared_error(y_test,y_pred)
    print(f"data relevance(r2): {score}\nMSE: {mse}")

In [139]:
multiple_linear_regression(np.array(raw_df[random.sample(list(raw_df.columns),3)]),y)

data relevance(r2): 25.189284931940637
MSE: 46.48153226323308


In [167]:
multiple_linear_regression(np.array(raw_df[random.sample(list(raw_df.columns),3)]),y)
print("IRRELEVANT DATA USED")

data relevance(r2): 67.18186773704224
MSE: 25.52091505362831
IRRELEVANT DATA USED


In [147]:
multiple_linear_regression(np.array(raw_df[random.sample(list(raw_df.columns),3)]),y)

data relevance(r2): 11.982034846080614
MSE: 88.30702468642795


In [149]:
multiple_linear_regression(np.array(raw_df[random.sample(list(raw_df.columns),3)]),y)

data relevance(r2): 16.70993024645593
MSE: 67.5084714177112


In [151]:
multiple_linear_regression(np.array(raw_df[random.sample(list(raw_df.columns),3)]),y)

data relevance(r2): 46.586829342690805
MSE: 40.717517349272796


In [153]:
multiple_linear_regression(np.array(raw_df[random.sample(list(raw_df.columns),3)]),y)

data relevance(r2): 26.072764790781044
MSE: 70.3160476707461


In [155]:
multiple_linear_regression(np.array(raw_df[random.sample(list(raw_df.columns),3)]),y)

data relevance(r2): 26.496241161303423
MSE: 49.73903157232549


In [157]:
multiple_linear_regression(np.array(raw_df[random.sample(list(raw_df.columns),3)]),y)

data relevance(r2): 30.62707944045591
MSE: 63.22987252905766


In [165]:
multiple_linear_regression(np.array(raw_df[random.sample(list(raw_df.columns),3)]),y)
print("RELEVANT DATA USED")

data relevance(r2): 28.3205701542115
MSE: 57.73405700129055
RELEVANT DATA USED
